---
title: "Оценка пространственной модели по российским данным"
author: Борис Демешев
date: "13 December 2014"
output: pdf_document
tags:
- mir
- trud
- may
lang: russian
---

Подгружаем пакеты:

```{r, message=FALSE, warning=FALSE}
library("ggplot2")
library("knitr")
library("MCMCpack")
library("pander")
library("dplyr")
library("MHadaptive")
library("mvtnorm")
library("psych")
library("pander")
library("knitr")
library("lme4")

library("microbenchmark") # test speed of various approaches
```


Загружаем результаты симуляций:

```{r}
pars <- readRDS("./estimation/pars_chain.Rds")
pars <- as.data.frame(pars)
pars <- dplyr::filter(pars, q>0)

n_sim_done <- nrow(pars)
pars <- mutate(pars, t = 1:n_sim_done)
```

Всего было `r n_sim_done` симуляций. График для $\rho$ весь:

```{r}
qplot(data=pars, t, rho, geom="line")
```

Отберем с 100-го наблюдения:
```{r}
pars <- dplyr::filter(pars, t>100)
```




```{r}
qplot(data=pars, rho, geom="density")
qplot(data=pars, alpha, geom="density")
qplot(data=pars, beta, geom="density")
qplot(data=pars, theta, geom="density")
qplot(data=pars, s2, geom="density")
qplot(data=pars, q, geom="density")
```

```{r}
qplot(data=pars, t, rho, geom="line")
qplot(data=pars, t, alpha, geom="line")
qplot(data=pars, t, beta, geom="line")
qplot(data=pars, t, theta, geom="line")
qplot(data=pars, t, s2, geom="line")
qplot(data=pars, t, q, geom="line")
```

Апостериорные средние и медианы:

```{r, results="asis"}
pars_sel <- dplyr::select(pars, rho, alpha, beta, theta, s2, q)
short_summ <- describe(pars_sel)[,2:5]
class(short_summ) <- "data.frame"
pander(short_summ)
```

HPD-интервалы:

```{r, results='asis'}
pander(HPDinterval(mcmc(pars_sel)))
```

